# Generated by Django 5.2.1 on 2025-05-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_structure', models.CharField(max_length=10)),
                ('month', models.DateField(help_text='Month and year')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variable_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_pay_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perform_category', models.CharField(choices=[('1', 'Exceeds Expectations(E)'), ('2', 'Meets Expectations(M)'), ('3', 'Partially Meets Expectations(PM)'), ('4', 'Below Expectations(BE)'), ('NA', 'Not Applicable(NA)')], max_length=2)),
                ('perform_comp_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reimbursement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_fee_earned', models.IntegerField(default=0)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
