# Generated by Django 5.2.1 on 2025-06-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payroll_generated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='reimbursement_proof',
            field=models.FileField(blank=True, help_text='Upload PDF proof for reimbursement', null=True, upload_to='reimbursement_proofs/'),
        ),
    ]
