# Generated by Django 5.2.1 on 2025-07-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payroll_reimbursement_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='generated_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
