# Generated by Django 5.2.1 on 2025-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Leave', 'Leave'), ('Half Leave', 'Half Leave'), ('Sick Leave', 'Sick Leave'), ('Holiday', 'Holiday'), ('Present', 'Present'), ('Half Absent', 'Half Absent'), ('Absent', 'Absent')], max_length=20, null=True),
        ),
    ]
