# Generated by Django 5.2.1 on 2025-05-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month and year')),
                ('working_days', models.IntegerField()),
                ('paid_leaves', models.IntegerField()),
                ('sick_leaves', models.IntegerField()),
                ('unpaid_leaves', models.IntegerField()),
                ('total_leaves_taken', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('days_worked', models.IntegerField()),
                ('total_paid_leaves_left', models.IntegerField(default=9)),
                ('total_sick_leaves_left', models.IntegerField(default=2)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
