# Generated by Django 5.2.1 on 2025-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='absent_days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='days_worked',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='paid_leaves',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='sick_leaves',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='total_leaves_taken',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='total_paid_leaves_left',
            field=models.FloatField(default=9),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='total_sick_leaves_left',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='unpaid_leaves',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='working_days',
            field=models.FloatField(),
        ),
    ]
