# Generated by Django 5.2.1 on 2025-06-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavedetails', '0002_alter_leavedetails_absent_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavedetails',
            name='absent_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='days_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='paid_leaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='sick_leaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='total_leaves_taken',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='total_paid_leaves_left',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='total_sick_leaves_left',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='unpaid_leaves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavedetails',
            name='working_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
