# Generated by Django 5.2.1 on 2025-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(default='jivass', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('account_type', models.CharField(choices=[('SBI', 'SBI'), ('NonSBI', 'Non-SBI')], default='SBI', max_length=10)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee')], max_length=10)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateField()),
                ('fee_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_structure', models.CharField(choices=[('fixed', 'Fixed Pay'), ('variable', 'Variable Pay')], default='fixed', max_length=10)),
            ],
        ),
    ]
