# Generated by Django 5.2.1 on 2025-05-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollrecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_type',
            field=models.CharField(choices=[('SBI', 'SBI'), ('NonSBI', 'Non-SBI')], default='SBI', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default='No address provided'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='jivass@jivass.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='fee_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pan_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='jivass', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_structure',
            field=models.CharField(choices=[('fixed', 'Fixed Pay'), ('variable', 'Variable Pay')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Leave', 'Leave'), ('Half Leave', 'Half Leave'), ('Sick Leave', 'Sick Leave'), ('Holiday', 'Holiday'), ('Present', 'Present'), ('Half Absent', 'Half Absent'), ('Absent', 'Absent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.CreateModel(
            name='LeaveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month and year')),
                ('working_days', models.IntegerField()),
                ('paid_leaves', models.IntegerField()),
                ('sick_leaves', models.IntegerField()),
                ('unpaid_leaves', models.IntegerField()),
                ('total_leaves_taken', models.IntegerField()),
                ('absent_days', models.IntegerField()),
                ('days_worked', models.IntegerField()),
                ('total_paid_leaves_left', models.IntegerField(default=9)),
                ('total_sick_leaves_left', models.IntegerField(default=2)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_structure', models.CharField(max_length=10)),
                ('month', models.DateField(help_text='Month and year')),
                ('base_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variable_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_pay_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perform_category', models.CharField(choices=[('1', 'Exceeds Expectations(E)'), ('2', 'Meets Expectations(M)'), ('3', 'Partially Meets Expectations(PM)'), ('4', 'Below Expectations(BE)'), ('NA', 'Not Applicable(NA)')], max_length=2)),
                ('perform_comp_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_fee_earned', models.IntegerField(default=0)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.employee')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
    ]
