# Generated by Django 5.2.1 on 2025-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='reason',
            new_name='description',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_id',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
