# Generated by Django 5.2.1 on 2025-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0002_rename_reason_leaverequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
