# Generated by Django 5.2.1 on 2025-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0003_leaverequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_period',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text='If half‑day leave, did they take morning or afternoon?', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Half Paid Leave', 'Half Paid Leave'), ('UnPaid Leave', 'UnPaid Leave'), ('Half UnPaid Leave', 'Half UnPaid Leave'), ('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave')], default='paid', max_length=20),
        ),
    ]
